### ISSUE TITLE
Auth flow not working

### ISSUE THREAD

**Issue by xaviablaza** [makisu/ghcli#12]
![image](https://user-images.githubusercontent.com/25378966/89227544-bbbeb300-d592-11ea-967f-da9ba198e7ad.png)

**Comment by xaviablaza** [comment]
@tomyfalgui I regenerated the oauth secret and it's not letting me go through the auth flow. I assume it's because the `accessToken` is saved somewhere and is reattempting to use those same credentials.

**Comment by xaviablaza** [comment]
@tomyfalgui A quick win for this would be to have a command that deletes the currently saved `accessToken`

**Comment by tomyfalgui** [comment]
Hi Xavi, I have the branch for the fix ready, but I don't seem to have push access to this repo.

**Comment by xaviablaza** [comment]
Would you be able to PR from a fork?
