### ISSUE TITLE
Delete branch on successful merge

### ISSUE THREAD

**Issue by xaviablaza** [makisu/ghcli#7]

**Comment by tomyfalgui** [comment]
for `pr-merge` ? or for both?

**Comment by xaviablaza** [comment]
For `label-merge` only. For context, this is my workflow:

- `feature1` is an open PR with `MERGE` label
- `feature2` is an open PR with `MERGE` label

I want to merge those into `master`, so I do:
```shell
ghcli label-merge -b master -l MERGE
```

Then, when I want to merge `master` into `production`, I can use `pr-merge`
```shell
ghcli pr-merge -b production -t internal-20200720
```

**Comment by tomyfalgui** [comment]
so in your example, the `master` branch should be deleted?

**Comment by tomyfalgui** [comment]
nvm, I misunderstood. 

in your example, ill be deleting feature1 and feature2, right?

**Comment by xaviablaza** [comment]
Yes, correct. You'd be deleting feature1 and feature2
